name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_COMMIT: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          COMMIT_BY_ME: True
          SHOW_EDITORS: False
          SHOW_LINES_OF_CODE: True
          SHOW_LOC_CHART: False
          TIMEZONE: America/Toronto


